import turtle
turtle.shape('turtle')
turtle.penup()
turtle.goto(50,0)
turtle.left(90)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(75)
turtle.end_fill()
turtle.penup()
turtle.goto(-50, 50)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(20, 50)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-25,10)
turtle.pendown()
turtle.width(5)
turtle.left(180)
turtle.forward(20)
turtle.penup()
turtle.goto(-60, -10)
turtle.pendown()
turtle.color('red')
turtle.circle(40, 180)
